<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>处理错误</title>
</head>

<body>

  <script>
    // 全局处理error 
    window.onerror = function (err) {
      console.log('window onerror', err);
    }


    // try... catch... 语法 捕获代码块中的错误
    try {
      throw SyntaxError('Hello, this is a SyntaxError')
    } catch (error) {
      console.log(error);
    }

    // 可选 catch 绑定 ,如果 我们不需要错误对象，可以省略 catch 语句中的参数
    try {
      throw SyntaxError('Hello, this is a SyntaxError')
    } catch {
      console.log('catch 绑定');
    }

    // finally 语句 无论 try 语句块中是否抛出错误，都会执行 finally 语句块中的代码
    try {
      throw SyntaxError('Hello, this is a SyntaxError')
    } catch {
      console.log('catch 绑定');
    } finally {
      console.log('finally 语句块');
    }

    // finally 和 return  
    function testFinally() {
      try {
        return 1;
      } catch {
        return 2;
      } finally {
        // finally 中的 return 会覆盖 try 中的 return
        return 3;
      }
    }

    const result = testFinally();
    console.log(result);

    // 如果try catch 中有return 出口， finally 子句会在 return 出口之前执行
    function testFinallyCall() {
      try {
        return 1;
      } catch {
        return 2;
      } finally {
        console.log('finally 语句块');
      }
    }
    testFinallyCall()
    // 拓展error


    const promise = new Promise((resolve, reject) => {
      throw new Error('Hello, this is a Error')

    })

    promise.then(res => {
      console.log(res);
    }).catch(err => {
      console.log(err);
    })

    // 包装Error
    // 继承Error对象 通过自定义的Error对象，可以为错误添加额外的信息
    class ValidationError extends Error {
      constructor(message) {
        super(message);
        this.name = 'ValidationError';
      }
    }

    function readUser(json) {
      const user = JSON.parse(json);
      console.log(user);
      if (!user.age) {
        throw new ValidationError('No field: age');
      }
      if (!user.name) {
        throw new ValidationError('No field: name');
      }

      return user;
    }
    try {
      readUser('{ "age": 25 }');

    } catch (error) {
      // 通过 instanceof 操作符，是否是我们需要处理的错误类型
      if (error instanceof ValidationError) {
        console.log(error.message);
      }
    }


  </script>

</body>

</html>